import { useState } from 'react';
import { useStore } from '../store/useStore';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { Button } from '../components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../components/ui/table';
import { AlertTriangle, Info, CheckCircle2, Ticket, Download } from 'lucide-react';
import { cn } from '../lib/utils';
import { Alert } from '../lib/mockData';

export default function AnomalyAlerts() {
  const { alerts, acknowledgeAlert, createTicket } = useStore();
  const [filter, setFilter] = useState<'All' | 'Open' | 'Acknowledged' | 'Ticket Created'>('Open');

  const filteredAlerts = filter === 'All' ? alerts : alerts.filter(a => a.status === filter);

  const getSeverityIcon = (severity: string) => {
    switch (severity) {
      case 'Critical': return <div className="p-1.5 bg-red-500/20 rounded-md border border-red-500/30"><AlertTriangle className="h-4 w-4 text-red-500" /></div>;
      case 'Warning': return <div className="p-1.5 bg-amber-500/20 rounded-md border border-amber-500/30"><AlertTriangle className="h-4 w-4 text-amber-500" /></div>;
      default: return <div className="p-1.5 bg-blue-500/20 rounded-md border border-blue-500/30"><Info className="h-4 w-4 text-blue-500" /></div>;
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'Open': return <Badge variant="destructive" className="bg-red-500 hover:bg-red-600 shadow-[0_0_10px_rgba(239,68,68,0.4)]">ACTION REQUIRED</Badge>;
      case 'Acknowledged': return <Badge variant="secondary" className="bg-blue-500/10 text-blue-600 border border-blue-500/30">INVESTIGATING</Badge>;
      case 'Ticket Created': return <Badge variant="outline" className="bg-emerald-500/10 border-emerald-500/50 text-emerald-600">TICKET DISPATCHED</Badge>;
      default: return <Badge>{status}</Badge>;
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
         <div className="flex space-x-2">
           {['Open', 'Acknowledged', 'Ticket Created', 'All'].map((f) => (
             <Button 
               key={f} 
               variant={filter === f ? 'default' : 'outline'}
               onClick={() => setFilter(f as any)}
               size="sm"
             >
               {f}
               {f === 'Open' && alerts.filter(a => a.status === 'Open').length > 0 && (
                 <span className="ml-2 bg-destructive text-destructive-foreground px-1.5 rounded-full text-xs">
                   {alerts.filter(a => a.status === 'Open').length}
                 </span>
               )}
             </Button>
           ))}
         </div>
         <Button variant="outline" size="sm">
           <Download className="h-4 w-4 mr-2" />
           Export CSV
         </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-2xl font-bold tracking-tight">Active Critical Faults</CardTitle>
          <CardDescription>Real-time telemetry assertions generated by AWS Lambda Rules Engine</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="rounded-xl border border-orange-200 bg-white shadow-sm overflow-hidden shadow-xl">
            <Table>
              <TableHeader className="bg-white/80 border-b border-orange-200">
                <TableRow className="border-none hover:bg-transparent">
                  <TableHead className="w-12"></TableHead>
                  <TableHead>Time</TableHead>
                  <TableHead>Vehicle Ref</TableHead>
                  <TableHead>Message</TableHead>
                  <TableHead>Action Recommended</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredAlerts.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={7} className="text-center py-8 text-muted-foreground">
                      No alerts found for this filter.
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredAlerts.map((alert: Alert) => (
                    <TableRow key={alert.id} className={cn(alert.status === 'Open' ? "bg-red-500/5" : "")}>
                      <TableCell>{getSeverityIcon(alert.severity)}</TableCell>
                      <TableCell className="text-xs text-muted-foreground whitespace-nowrap">
                        {new Date(alert.timestamp).toLocaleTimeString()}
                      </TableCell>
                      <TableCell>
                        <div className="font-medium">{alert.vehicleId}</div>
                        <div className="text-xs text-muted-foreground">{alert.batteryId}</div>
                      </TableCell>
                      <TableCell className="max-w-[200px] truncate" title={alert.message}>
                        {alert.message}
                      </TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {alert.recommendedAction}
                      </TableCell>
                      <TableCell>{getStatusBadge(alert.status)}</TableCell>
                      <TableCell className="text-right">
                        {alert.status === 'Open' && (
                          <div className="flex justify-end space-x-2">
                             <Button size="sm" variant="outline" onClick={() => acknowledgeAlert(alert.id)}>
                               <CheckCircle2 className="h-4 w-4 mr-1" /> Ack
                             </Button>
                             <Button size="sm" onClick={() => createTicket(alert.id)}>
                               <Ticket className="h-4 w-4 mr-1" /> Ticket
                             </Button>
                          </div>
                        )}
                        {alert.status === 'Acknowledged' && (
                           <Button size="sm" onClick={() => createTicket(alert.id)}>
                             <Ticket className="h-4 w-4 mr-1" /> Ticket
                           </Button>
                        )}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
